# Generated by Django 4.2.30 on 2026-08-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_AI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai',
            name='has_times',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
