# Generated by Django 4.2.30 on 2026-08-03 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('create_AI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='training_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_saved', models.CharField(max_length=255)),
                ('name', models.IntegerField()),
                ('ai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_AI.ai')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
