# Generated by Django 4.2.30 on 2026-08-08 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('create_AI', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='training_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_saved', models.CharField(max_length=255)),
                ('name2', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('ai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_AI.ai')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AI_values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name2', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('value_checks', models.JSONField(blank=True, default=list)),
                ('value_answers', models.JSONField(blank=True, default=list)),
                ('group', models.JSONField(blank=True, default=list)),
                ('ai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_AI.ai')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
