# Generated by Django 4.2.30 on 2026-08-08 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('update_AI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai_values',
            name='training_text',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='update_AI.training_text'),
            preserve_default=False,
        ),
    ]
