# Generated by Django 4.2.30 on 2026-08-03 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update_AI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training_text',
            old_name='name',
            new_name='name2',
        ),
    ]
