# Generated by Django 4.2.30 on 2026-08-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_AI', '0002_rename_name_training_text_name2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training_text',
            name='name2',
            field=models.CharField(max_length=255),
        ),
    ]
