# Generated by Django 4.2.30 on 2026-08-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_AI', '0003_alter_training_text_name2'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_text',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
