# Generated by Django 4.2.30 on 2026-08-25 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('create_AI', '0001_initial'),
        ('update_AI', '0003_ai_values_created_at_ai_values_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='times_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time1', models.DateTimeField()),
                ('time2', models.DateTimeField()),
                ('time3', models.DateTimeField()),
                ('ai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_AI.ai')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
