# Generated by Django 4.2.30 on 2026-09-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_AI', '0004_times_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai_values',
            name='duplicate',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
